format = """
$username\
$hostname\
$localip\
$container\
$sudo\
$directory\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$status\
$cmd_duration\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$crystal\
$line_break\
$shell\
$character"""

right_format = """
$memory_usage\
$battery\
$time\
 """
# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'


# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = 'green bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = true
ssh_symbol = '🌐 '
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = false

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false

# ~/.config/starship.toml
[container]
style = 'bold blue'
format = '[$symbol \[$name\]]($style) '

[directory]
style = 'bold cyan'
read_only_style = 'bold red'
truncation_length = 8
truncate_to_repo = true
truncation_symbol = '…/'
home_symbol = '~'
read_only = '🔒-ROM'
format = '[$path]($style)[$read_only]($read_only_style) '

[c]
format = "[\n$symbol($version(-$name) )]($style)"

[cmake]
format = "[\n$symbol($version(-$name) )]($style)"

[cobol]
format = "[\n$symbol($version(-$name) )]($style)"

[daml]
format = "[\n$symbol($version(-$name) )]($style)"

[dart]
format = "[\n$symbol($version(-$name) )]($style)"

[deno]
format = "[\n$symbol($version(-$name) )]($style)"

[dotnet]
format = "[\n$symbol($version(-$name) )]($style)"

[elixir]
format = "[\n$symbol($version(-$name) )]($style)"

[elm]
format = "[\n$symbol($version(-$name) )]($style)"

[erlang]
format = "[\n$symbol($version(-$name) )]($style)"

[fennel]
format = "[\n$symbol($version(-$name) )]($style)"

[golang]
format = "[\n$symbol($version(-$name) )]($style)"

[guix_shell]
format = "[\n$symbol($version(-$name) )]($style)"

[haskell]
format = "[\n$symbol($version(-$name) )]($style)"

[haxe]
format = "[\n$symbol($version(-$name) )]($style)"

[helm]
format = "[\n$symbol($version(-$name) )]($style)"

[java]
format = "[\n$symbol($version(-$name) )]($style)"

[julia]
format = "[\n$symbol($version(-$name) )]($style)"

[kotlin]
format = "[\n$symbol($version(-$name) )]($style)"

[gradle]
format = "[\n$symbol($version(-$name) )]($style)"

[lua]
format = "[\n$symbol($version(-$name) )]($style)"

[nim]
format = "[\n$symbol($version(-$name) )]($style)"

[nodejs]
format = "[\n$symbol($version(-$name) )]($style)"

[ocaml]
format = "[\n$symbol($version(-$name) )]($style)"

[opa]
format = "[\n$symbol($version(-$name) )]($style)"

[perl]
format = "[\n$symbol($version(-$name) )]($style)"

[php]
format = "[\n$symbol($version(-$name) )]($style)"

[pulumi]
format = "[\n$symbol($version(-$name) )]($style)"

[purescript]
format = "[\n$symbol($version(-$name) )]($style)"

[python]
format = "[\n$symbol($version(-$name) )]($style)"

[raku]
format = "[\n$symbol($version(-$name) )]($style)"

[rlang]
format = "[\n$symbol($version(-$name) )]($style)"

[red]
format = "[\n$symbol($version(-$name) )]($style)"

[ruby]
format = "[\n$symbol($version(-$name) )]($style)"

[rust]
format = "[\n$symbol($version(-$name) )]($style)"

[scala]
format = "[\n$symbol($version(-$name) )]($style)"

[swift]
format = "[\n$symbol($version(-$name) )]($style)"

[terraform]
format = "[\n$symbol($version(-$name) )]($style)"

[vlang]
format = "[\n$symbol($version(-$name) )]($style)"

[vagrant]
format = "[\n$symbol($version(-$name) )]($style)"

[zig]
format = "[\n$symbol($version(-$name) )]($style)"

[buf]
format = "[\n$symbol($version(-$name) )]($style)"

[nix_shell]
format = "[\n$symbol($version(-$name) )]($style)"

[conda]
format = "[\n$symbol($version(-$name) )]($style)"

[meson]
format = "[\n$symbol($version(-$name) )]($style)"

[spack]
format = "[\n$symbol($version(-$name) )]($style)"

[crystal]
format = "[\n$symbol($version(-$name) )]($style)"

[memory_usage]
disabled = false
threshold = -1
symbol = '🐏'
style = 'bold dimmed green'
format = "$symbol [${ram_pct}( ${swap_pct})]($style) "

[env_var.LAST_EXIT_CODE]
default = '0'
style = 'bold green'
format = '[\[$env_value\] ]($style)'

[sudo]
style = 'bold green'
disabled = false
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
format = 'in [$duration](bold yellow)'

[[battery.display]]
threshold = 100
style = 'bold white'

[time]
disabled = false
format = '🕙[ $time ]($style) '
time_format = '%R'
style = 'blue'
utc_time_offset = 'local'
time_range = '-'

[status]
style = 'bold red'
symbol = '❌'
success_symbol = '🟢'
format = '[$symbol \[$status\]]($style) '
map_symbol = true
disabled = false

[shell]
fish_indicator = ''
powershell_indicator = '_'
unknown_indicator = '?'
style = 'green bold'
disabled = false
